accession, archival_objects, assessments, classifications, classifica…
notch8-old/archivesspace pull request #48
Opened 2022-09-09 19:54 UTC by arnoldc94

# Summary
![image](https://user-images.githubusercontent.com/84541944/189431274-0082732c-0a2c-4bd6-b219-30b6f532e326.png)
![image](https://user-images.githubusercontent.com/84541944/189431330-2c340e01-6736-476d-bbdd-f6566ab5aa2a.png)

# Screenshots
Assessments
<details>
<img width="922" alt="Screen Shot 2022-09-08 at 7 29 27 PM" src="https://user-images.githubusercontent.com/84541944/189430420-0826f59a-f301-4487-9206-2fcfd85d770d.png">
<img width="894" alt="Screen Shot 2022-09-08 at 7 30 23 PM" src="https://user-images.githubusercontent.com/84541944/189430431-36fe6492-6fe2-4eae-acb8-4ea28f259fc4.png">
<img width="880" alt="Screen Shot 2022-09-08 at 7 31 41 PM" src="https://user-images.githubusercontent.com/84541944/189430436-1f89928b-0ebc-494c-ac1d-9c7d0ec7714e.png">
ssments </details>

Classifications
<details>
<img width="882" alt="Screen Shot 2022-09-09 at 6 33 42 AM" src="https://user-images.githubusercontent.com/84541944/189430767-6fa83694-016b-4360-9d90-c61e7e57d3e6.png">
<img width="865" alt="Screen Shot 2022-09-09 at 6 34 37 AM" src="https://user-images.githubusercontent.com/84541944/189430768-b922076c-5d68-4d07-b48a-9019b4e1eaff.png">
<img width="882" alt="Screen Shot 2022-09-09 at 6 34 49 AM" src="https://user-images.githubusercontent.com/84541944/189430770-4495fd86-0c90-4092-a546-603137da0965.png">
</details>

Classification_term 
<details>
<img width="858" alt="Screen Shot 2022-09-09 at 6 40 35 AM" src="https://user-images.githubusercontent.com/84541944/189430826-2a0d6cfb-5197-4e5a-9c62-c0defb54f1bf.png">
<img width="872" alt="Screen Shot 2022-09-09 at 6 41 39 AM" src="https://user-images.githubusercontent.com/84541944/189430828-afb2366a-e0b5-4a73-aa53-ac9a73435662.png">
<img width="869" alt="Screen Shot 2022-09-09 at 6 42 05 AM" src="https://user-images.githubusercontent.com/84541944/189430830-51da4ff0-4d3a-4f25-b097-b84b234fa0ee.png">
</details>

Digital_object_component
<details>
<img width="1155" alt="Screen Shot 2022-09-08 at 8 00 04 PM" src="https://user-images.githubusercontent.com/84541944/189430885-4c239457-8e9a-4772-849d-47f02384c62a.png">
<img width="1155" alt="Screen Shot 2022-09-08 at 8 00 26 PM" src="https://user-images.githubusercontent.com/84541944/189430887-28c782d4-2c6f-40be-8bd1-dfae97e19ee0.png">
<img width="1170" alt="Screen Shot 2022-09-08 at 8 08 22 PM" src="https://user-images.githubusercontent.com/84541944/189430889-79f3949a-eeaa-4bdf-901d-3a1cb03cd064.png">
<img width="1158" alt="Screen Shot 2022-09-08 at 8 11 12 PM" src="https://user-images.githubusercontent.com/84541944/189430890-e8cb0a81-8387-44aa-876c-99f6fa6c9abd.png">
<img width="1152" alt="Screen Shot 2022-09-08 at 8 12 53 PM" src="https://user-images.githubusercontent.com/84541944/189430891-1ce89191-650c-460a-aae3-f1b6dd2bcb2c.png">
<img width="797" alt="Screen Shot 2022-09-09 at 9 06 27 AM" src="https://user-images.githubusercontent.com/84541944/189430892-40433c54-5ab9-442a-a9a0-ae0379bac6d9.png">
<img width="806" alt="Screen Shot 2022-09-09 at 9 13 13 AM" src="https://user-images.githubusercontent.com/84541944/189430893-51833c6d-b71d-4740-9d95-ee9f34308dd8.png">
</details>

Accession
<details><img width="1187" alt="Screen Shot 2022-09-09 at 6 21 04 AM" src="https://user-images.githubusercontent.com/84541944/189430945-d780a11e-d839-4ca8-951a-144e4ac99fe5.png">
<img width="906" alt="Screen Shot 2022-09-09 at 6 27 42 AM" src="https://user-images.githubusercontent.com/84541944/189430948-9bf58f23-5a26-4f58-9485-43b34d618509.png">
<img width="883" alt="Screen Shot 2022-09-09 at 6 28 02 AM" src="https://user-images.githubusercontent.com/84541944/189430950-38764540-2641-4236-aac1-dec7cb6da097.png">
<img width="882" alt="Screen Shot 2022-09-09 at 6 28 16 AM" src="https://user-images.githubusercontent.com/84541944/189430952-220e9430-3121-428d-82a9-410db0c89f26.png">
<img width="877" alt="Screen Shot 2022-09-09 at 6 28 29 AM" src="https://user-images.githubusercontent.com/84541944/189430953-c5125aea-97e4-4eed-8334-2bf10cd985fd.png">
<img width="850" alt="Screen Shot 2022-09-09 at 6 30 32 AM" src="https://user-images.githubusercontent.com/84541944/189430956-97ecb614-d111-4e4e-8077-504b298ef05c.png">

</details>

archival_objects: Could not navigate to this element code. I implemented the fix for the bug in the code. There are no screenshots that can be provided.

# Related Tickets
Ticket 90 - https://gitlab.com/notch8/archivesspace/-/issues/90

# Acceptance Criteria
I can visit the following pages without hitting a rails error/ Success message displays properly

assessments
- [ ] Create
- [ ] Update
- [ ] Delete
classifications
- [ ] Create
- [ ] Update
- [ ] Delete
classification_term
- [ ] Create
- [ ] Update
- [ ] Delete
digital_object_component
- [ ] Create
- [ ] Update
- [ ] Delete
- [ ] Suppress
- [ ] Unsuppress
accession
- [ ] Show
- [ ] Create
- [ ] Update
- [ ] Delete
- [ ] Suppress
- [ ] Unsuppress
archival_object

- [ ] Show
- [ ] Create
- [ ] Update
- [ ] Delete
- [ ] Suppress
- [ ] Unsuppress
- [ ] Unpublish
- [ ] Publish
- [ ] Transfer

2022-09-09 22:47 UTC, orangewolf requested changes
Really solid work overall, but the changes to en.yml need to be reversed and the hashes in the controllers need to be updated to match them.

2022-09-09 22:47 UTC, orangewolf commented on frontend/config/locales/en.yml
> -        created: Accession <strong>%{accession_display_string}</strong> created
we need to change the hashes above to use these same strings, because all other translations will use these same substitution strings and we don't want to change them all. So for this one the method above would go from 
```
flash[:success] = t("accession._frontend.messages.created", accession_title: @accession.title)
```
to
```
flash[:success] = t("accession._frontend.messages.created", accession_display_string: @accession.title)
```

This is true of all the ones that were changed in this file.

2022-09-11 00:31 UTC, orangewolf commented on frontend/config/locales/en.yml
> +        published: "The Archival Object <strong>%{archival_object_display_string}</strong>, its children, subrecords and components have been published"
these ones should be unchanged also ;-)

2022-09-12 14:57 UTC, arnoldc94 commented on frontend/config/locales/en.yml
> +        published: "The Archival Object <strong>%{archival_object_display_string}</strong>, its children, subrecords and components have been published"
Made the requested change

2022-09-12 16:22 UTC, orangewolf approved these changes

2022-09-12 16:22 UTC, merged